stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
#
#create-package:
#  stage: create
#  image: maven:3.8.3-openjdk-17
#  script:
#    - mvn clean package

# A simple comment
build-job:  # This job runs in the build stage, which runs first.
  image: docker@sha256:c8bb6fa5388b56304dd770c4bc0478de81ce18540173b1a589178c0d31bfce90
  services:
    - docker:dind@sha256:c8bb6fa5388b56304dd770c4bc0478de81ce18540173b1a589178c0d31bfce90  
  stage: build
  script:
    - echo $DOCKER_USERNAME echo $DOCKER_PASSWORD
    - docker login registry.gitlab.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t registry.gitlab.com/gsmi572/gs-pcs .
    - docker push registry.gitlab.com/gsmi572/gs-pcs


# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  
 
#   script:
#     - echo "Deploying application..."
#     - curl -X POST $DEPLOY_HOOK_URL
#     - echo "Application successfully deployed."

  only:
      - d387


